
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - frontend

  rust-service:
    build:
      context: ./api/
     
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  frontend:
  backend:
